### ISSUE TITLE
How to include icon?

### ISSUE THREAD

**Issue by schlich** [evidence-dev/datasource-template#1]
Hello,

I'm working on building a connector for Kaggle.  In step 3 in the README, it says we can optionally include an icon in the package.json. I've found the kaggle icon on simple icons but not sure how to add it to the project config!

thanks in advance!

**Comment by ItsMeBrianD** [comment]
Hey @schlich!

Sorry for the (very) late response to this, I've added an example in the README for instructions here!

**Comment by archiewood** [comment]
For example:

```
  "evidence": {
    "datasources": [
      "clickhouse"
    ],
    "icon": "Clickhouse"
  },
```

If your icon name is invalid (ie does not exist in SteezeUI), you will get an error like this:

```
Datasource package "evidence-connector-clickhouse" is an invalid Evidence plugin, run again with --debug for more information
```
